apiVersion: v1
kind: Service
metadata:
  name: content-enrichment-service
  labels:
    app: content-enrichment
spec:
  type: LoadBalancer
  selector:
    app: content-enrichment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
