apiVersion: v1
kind: ConfigMap
metadata:
  name: content-enrichment-config
data:
  GOOGLE_CLOUD_PROJECT: "content-enrichment-488220"
  MODEL_BUCKET: "content-enrichment-488220"
  MODEL_PATH: "models/best_model.pkl"
  LOG_LEVEL: "INFO"
